name: parse latest dnsmasq-china-list
on:
  schedule:
    - cron:  '0 10 * * *'
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ github.token }}
      - name: Fetch latest dnsmasq-china-list
        run: |
          wget -O - https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf | tee accelerated-domains.china.ali.conf accelerated-domains.china.tencent.conf accelerated-domains.china.default.ali.conf accelerated-domains.china.default.tencent.conf >/dev/null
          ls ${{ github.workspace }}
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with: 
          find: "server="
          replace: "["
          regex: false
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "114.114.114.114"
          replace: "]https://doh.pub/dns-query"
          include: "*.tencent.conf"
          regex: false
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "114.114.114.114"
          replace: "]https://dns.alidns.com/dns-query"
          include: "*.ali.conf"
          regex: false
      - name: dns file with default dns
        run: |
          echo "https://dns10.quad9.net/dns-query" >> accelerated-domains.china.default.*.conf
          echo "https://101.6.6.6/dns-query" >> accelerated-domains.china.default.*.conf
          echo "https://dns.tuna.tsinghua.edu.cn:8443/dns-query" >> accelerated-domains.china.default.*.conf
          echo "https://101.6.6.6:8443/dns-query" >> accelerated-domains.china.default.*.conf
          echo "https://dns.cloudflare.com/dns-query" >> accelerated-domains.china.default.*.conf
          echo "https://dns.google/dns-query" >> accelerated-domains.china.default.*.conf
          echo "https://doh.mk/dns-query" >> accelerated-domains.china.default.*.conf

      - name: Commit latest release version
        run: |
          git config --global user.name 'Snorlax'
          git config --global user.email '24599209+Mr-Sheep@users.noreply.github.com'
          git commit -am "daily update from dnsmasq-china-list"
          git push